name: Rust CI

on:
  push:
    branches:
      - master
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Universal macOS build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup target add aarch64-apple-darwin
      - run: cargo build --target aarch64-apple-darwin
      - run: ./target/aarch64-apple-darwin/debug/kitty --help
