name: Rust CI

on:
  push:
    branches:
      - master
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: kitty.exe
            target: x86_64-pc-windows-msvc
          - os: ubuntu-latest
            artifact_name: kitty
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            artifact_name: kitty
            target: x86_64-apple-darwin
          - os: macos-latest
            artifact_name: kitty
            target: aarch64-apple-darwin

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install latest Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          override: true

      - name: Add build target
        run: rustup target add ${{ matrix.target }}

      - name: Build binary
        run: cargo +nightly build --release --target ${{ matrix.target }} --out-dir kitty-artifacts -Z unstable-options

      - name: Strip binary
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: strip kitty-artifacts/${{ matrix.artifact_name }}

      - name: Show output
        run: |
          echo "${{ matrix.target }}-${{ matrix.artifact_name }}"
          ls -l kitty-artifacts

      # - name: Upload binary to release
      #   uses: svenstaro/upload-release-action@v1-release
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     file: kitty-artifacts/${{ matrix.artifact_name }}
      #     asset_name: ${{ matrix.target }}-${{ matrix.artifact_name }}
      #     tag: ${{ github.event.release.tag_name }}
